### ISSUE TITLE
Distortion / soft clipping

### ISSUE THREAD

**Issue by riban-bw** [owingsbj/ModSynth#13]
When the soft clipping feature was enhanced to provide a more accurate representation of analogue amplifier clipping, the feature was renamed, "Distortion" which I don't think is as descriptive (or evocative) as "Soft Clipping". With "Distortion" disabled the output can be driven into hard clipping (distortion) where as with "Distortion" enabled the output is limited with a softer distortion. I would recommend reverting to the title "Soft Clipping".

**Comment by owingsbj** [comment]
Okay, I'll change it back to Soft Clip.  This setting makes the amp module simulate a tube amplifier.  It will distort on any value beyond +/- 0.5 and falls off asymptotically, like in this graph:

![image](https://user-images.githubusercontent.com/12424301/48110013-b89c6480-e1fe-11e8-8e28-a807b0212332.png)

**Comment by owingsbj** [comment]
5.9 is delivered, so closing this issue.  Reopen if it's still a problem.
