### ISSUE TITLE
LFO rate too coarse

### ISSUE THREAD

**Issue by riban-bw** [owingsbj/ModSynth#15]
The recent change to consolidate the coarse and fine adjustment of LFO rate made this module easier to use but has left the adjustment too coarse. It is particularly difficult to adjust the low end. The previous implementation was sub-optimal with too wide a range and non-intuitive configuration.

**Comment by owingsbj** [comment]
I made changes that should have made this more sensitive to adjust on the low end.  I rechecked the implementation and see that the minimal value is 0.01hz.  It should be 0.0001hz so I'll fix that in ModSynth 5.9.

**Comment by owingsbj** [comment]
5.9 is delivered, so closing this issue.  Reopen if it's still a problem.

**Comment by riban-bw** [comment]
That is much better thanks. I think the high end could be increase though. I am running out of speed. Effects are limited and very fast arpeggios are not achievable. I guess that should be the subject of another issue.
