### ISSUE TITLE
Android 8.1 reduction in performance

### ISSUE THREAD

**Issue by riban-bw** [owingsbj/ModSynth#17]
My Moto G5 Android phone updated from Android 7.0 to Android 8.1 and I have observed substantial reduction in performance in ModSynth. An instrument that was able to achieve 6 note polyphony before suffering distortion is now struggling to achieve 3 note polyphony. Android 8.x provides low-latency audio. I wonder if this is relevant?

**Comment by owingsbj** [comment]
Is this still true on ModSynth 5.8?

**Comment by riban-bw** [comment]
5.8 is pretty much unusable on my Moto G5 recently updated to Andorid 8.1. It was capable of fairly complex instruments with 5 note polyphony when it was running Android 7.0 (and earlier version of ModSynth). The problem may be related to other issues such as changes to patches not working (see issue #19) but right now the app is unusable! Is there a way to revert to a previous (known working) version to compare performance or do you think that recent fixes are required to resolve the apparent change in resource handling in 8.1?

**Comment by owingsbj** [comment]
The change to Android 8.1 switches ModSynth to use AAudio (from OpenSL).  I'd rather not switch it back so hopefully I can find why it is running slower.  One observation you noted in email was that it was using a slower CPU.  I'll add a change to set the CPU affinity to a high-numbered CPU (which I read are the faster CPUs on an octa-core).   I'll also make some general performance improvements.  You can expect these updates in ModSynth 5.9

**Comment by owingsbj** [comment]
5.9 is delivered, so closing this issue.  Reopen if it's still a problem.

**Comment by riban-bw** [comment]
Confirmed fixed, thanks.
