### ISSUE TITLE
Mixer multiply not working for newly created instrument

### ISSUE THREAD

**Issue by riban-bw** [owingsbj/ModSynth#19]
I have an existing instrument which has a mixer block configured as multiplier. This mixer is fed from an envelope (input 1) and an LFO (input 3). The output feeds the gain of an Amp block. Input 1 and Bias are set to 100% which provides a through path for the envelope to control the amplifier. Input 3 level then adds LFO modulation (tremelo). If I create a new instrument with modsynth v5.8 then this configuration fails with no audio being passed out.

**Comment by riban-bw** [comment]
Added zip with working and broken versions of multiply block.
[ModSynth_Multiply_issue.zip](https://github.com/owingsbj/ModSynth/files/2561002/ModSynth_Multiply_issue.zip)

**Comment by owingsbj** [comment]
5.9 is delivered, so closing this issue.  Reopen if it's still a problem.

**Comment by riban-bw** [comment]
Confirmed fixed, thanks.
