### ISSUE TITLE
MIDI notes get stuck on

### ISSUE THREAD

**Issue by riban-bw** [owingsbj/ModSynth#21]
Sometimes a MIDI note off is missed, leaving a note sounding. Replaying the same note results in the note being cleared when released.

**Comment by owingsbj** [comment]
I tried to reproduce this with no luck.  I just released 5.10 with a fix in the only place I could see that might cause this.  Could you test it again with 5.10 and let me know if still happens?   Also, any hints on how to reproduce would be appreciated.  Is it a certain number of voices?

**Comment by pr1ntf** [comment]
I was having this same issue on an older version. Sometimes I found that simoly mashing a bunch of keys would reset it. 

After updating, however, I haven't run into this issue again.

**Comment by riban-bw** [comment]
I haven't encountered this for a while so will close this issue. I can re-open or raise new issue if it reoccurs.
