### ISSUE TITLE
MIDI Sustain

### ISSUE THREAD

**Issue by pr1ntf** [owingsbj/ModSynth#26]
I noticed I'm not able to use a sustsain pedal when using a hardware MIDI keyboard. 

This would be great for things like the harmonics oscillator source.

Checking the sustain box in the keyboard module just sustains every note. 

PS: thanks for open sourcing!

**Comment by riban-bw** [comment]
This may best be resolved by making Keyboard module's sustain parameter configurable for MIDI control with default CC=64. I have a patch to do this which I can submit as a PR. I just need to fix a couple of bits. I would suggest having a few default controllers, e.g. CC 7 for amp volume.
