### ISSUE TITLE
Many errors about missing resources

### ISSUE THREAD

**Issue by riban-bw** [owingsbj/ModSynth#30]
Upon loading project (and Eclipse attempts to compile) I see lots of similar messages like, "ModSynth\res\layout\amppane.xml:116: error: Error: No resource found that matches the given name (at 'button' with value '@drawable/btn_check')." and "ModSynth\res\layout\dividerpane.xml:33: error: No resource identifier found for attribute 'rangeEnd' in package 'com.gallantrealm.modsynth'".

**Comment by riban-bw** [comment]
It looks like some of the resource files are missing from git repro.

**Comment by riban-bw** [comment]
The missing resources appear to be in MyAndroid. Should ModSynth have submodule links to MyAndroid (and presumably also MySynth)?

**Comment by riban-bw** [comment]
Ah! It looks like importing all three projects (ModSynth, MySynth & MyAndroid) into a single Eclipse workspace resolves this. I don't know if this confusion is due to my ignorance of best practice within Eclipse or a lack of documentation around this element. If the former then feel free to close this issue. If the latter then please add something to the README or wiki or other documentation.

**Comment by owingsbj** [comment]
I updated the readme to mention the dependencies on MySynth and MyAndroid.

**Comment by riban-bw** [comment]
Perfect!
