### ISSUE TITLE
On screen keyboard not showing press state

### ISSUE THREAD

**Issue by riban-bw** [owingsbj/ModSynth#34]
The github head version (6?) of ModSynth does not show onscreen keyboard keys being pressed. If a key is pressed when sustain is enabled then the key will change to show it is pressed. Looks like this has not been ported to the newly abstracted code. Sorry if this is a work in progress but probably worth reporting things that are not working so that they don't get lost and to give a warm feeling when resolving issues here in github.

**Comment by owingsbj** [comment]
should be fixed now
